Add test of enum and typedef with same name
    error[E0428]: the name `Enum` is defined multiple times
      --> bindgen-tests/tests/expectations/tests/enum-typedef.rs:10:1
       |
    9  | pub type Enum = ::std::os::raw::c_uint;
       | --------------------------------------- previous definition of the type `Enum` here
    10 | pub type Enum = i16;
       | ^^^^^^^^^^^^^^^^^^^^ `Enum` redefined here
       |
       = note: `Enum` must be defined only once in the type namespace of this module

    error[E0428]: the name `TypedefFirst` is defined multiple times
      --> bindgen-tests/tests/expectations/tests/enum-typedef.rs:13:1
       |
    11 | pub type TypedefFirst = i16;
       | ---------------------------- previous definition of the type `TypedefFirst` here
    12 | pub const TypedefFirst_Variant2: TypedefFirst = 0;
    13 | pub type TypedefFirst = ::std::os::raw::c_uint;
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `TypedefFirst` redefined here
       |
       = note: `TypedefFirst` must be defined only once in the type namespace of this module